(function(n,b,j,k){function f(a,b){E&&E.count&&E.count("aui:"+a,b===0?0:b||(E.count("aui:"+a)||0)+1)}function i(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function g(a,b,c,d){b=b&&c?b+a+c:b||c;return d?g(a,b,d):b}function e(a,b){try{Object.defineProperty(n,a,{value:b})}catch(c){n[a]=b}}function d(){return setTimeout(D,0)}function c(a,b){var c=a.length,e=c,f=function(){e--||(F.push(b),v||(d(),v=!0))};for(f();c--;)A[a[c]]?f():(m[a[c]]=m[a[c]]||[]).push(f)}
function a(a,c,d,e){var f=b.createElement(a?"script":"link");i(f,"error",e);a?(f.type="text/javascript",f.async=!0,d&&(c.indexOf("images/I")!==-1||/AUIClients/.test(c))&&f.setAttribute("crossorigin","anonymous"),f.src=c):(f.rel="stylesheet",f.href=c);b.getElementsByTagName("head")[0].appendChild(f)}function h(b,c){return function(d){function e(){a(c,d,g,function(){g?(g=!1,f("resource_retry"),e()):(f("resource_error"),b.log("Asset failed to load: "+d))})}if(z[d])return!1;z[d]=!0;f("resource_count");
var g=!0;return!e()}}function l(a,b,d,e,f){return function(g,h){var i=f||this;typeof g==="function"&&(h=g,g="anon"+G++);var j=i.guardError(g,function(){for(var c=[],d=0;d<a.length;d++)c[d]=H.hasOwnProperty(a[d])?H[a[d]]:k;d=null;e?d=h:typeof h==="function"&&(d=h.apply(n,c));if(b){H[g]=d;c=g;for(A[c]=!0;(m[c]||[]).length;)m[c].shift()();delete m[c]}});H.hasOwnProperty(g)&&i.error("Component already registered",g);H[g]=k;d?j():c(a,j)}}function o(a){return function(){return{execute:l(arguments,!1,a,
!1,this),register:l(arguments,!0,a,!1,this)}}}function p(a,b){return function(c,d){var e=this;return function(){d||(d=c,c=k);try{d.apply(this,arguments)}catch(f){var h=n.console;if(h&&h.error&&e.log(f,b,c))h.error(g(String.fromCharCode(10),g(": ",a,c,f.message),f.stack||f));else throw f instanceof Error?f:Error(g(": ",a,c,f));}}}}function s(a){this.log=function(b,c,d){var e=n.ueLogError;return e?(e({message:b,logLevel:c||"ERROR",attribution:g(":",a,d)}),!0):!1};this.error=function(b,c,d,e){throw Error(g(" @ ",
g(":",e,b),g(":",a,c,d)));};this.guardError=p(a);this.guardFatal=p(a,"FATAL");this.load={js:h(this,!0),css:h(this)}}function r(a,b){for(var c=a.className.split(" "),d=c.length;d--;)if(c[d]===b)return;a.className+=" "+b}function q(a,b){for(var c=a.className.split(" "),d=[],e;(e=c.pop())!==k;)e&&e!==b&&d.push(e);a.className=d.join(" ")}function w(a){try{return a()}catch(b){return!1}}function t(){if(sa){var a=n.innerWidth?{w:n.innerWidth,h:n.innerHeight}:{w:I.clientWidth,h:I.clientHeight},b=!1;Math.abs(a.w-
ta.w)>5||a.h-ta.h>50?(ta=a,ua=4,(b=O.mobile||O.tablet?a.w>a.h:a.w>=1250)?r(I,"a-ws"):q(I,"a-ws")):ua--&&(wa=setTimeout(t,16))}}function u(){clearTimeout(wa);ua=4;t()}function x(a){(sa=a===k?!sa:!!a)&&t()}function C(){return sa}var y=n.AmazonUIPageJS||n.P;if(y&&y.when&&y.register)throw Error("A copy of P has already been loaded on this page.");var E=n.ue;E&&E.tag&&(E.tag("aui"),E.tag("aui:aui_build_date:3.15.7.4-2015-07-30"));var B=j.now=j.now||function(){return+new j},F=[],v=!1,D;D=function(){for(var a=
d(),b=B();F.length;)if(F.shift()(),B()-b>50)return;clearTimeout(a);v=!1};(function(a){try{return a.test(navigator.userAgent)}catch(b){return!1}})(/OS 6_[0-9]+ like Mac OS X/i)&&i(n,"scroll",d);var A={},m={},z={},G=0,H={},M;s.prototype={declare:l([],!0,!0,!0),register:l([],!0),execute:l([]),AUI_BUILD_DATE:"3.15.7.4-2015-07-30",when:o(),now:o(!0),trigger:function(a,b){var c=n.aPageStart||NaN,d=B(),c={data:b,pageElapsedTime:d-c,triggerTime:d};this.declare(a,c);M&&M(a,c)},handleTriggers:function(a){M&&
this.error("Trigger handler already registered");M=a},attributeErrors:function(a){return new s(a)}};e("AmazonUIPageJS",new s);e("P",n.AmazonUIPageJS);if(b.addEventListener){var K;b.addEventListener("DOMContentLoaded",K=function(){n.AmazonUIPageJS.trigger("a-domready");b.removeEventListener("DOMContentLoaded",K,!1)},!1)}var I=b.documentElement,U;try{U=navigator.userAgent}catch(ba){U=""}var X=function(){var a="O,ms,Moz,Webkit".split(","),c=b.createElement("div");return{testGradients:function(){c.style.cssText=
("background-image:"+"-webkit- ".split(" ").join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+a.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);return c.style.backgroundImage.indexOf("gradient")>-1},test:function(b){for(var d=b.charAt(0).toUpperCase()+b.substr(1),b=(a.join(d+" ")+d+" "+b).split(" "),d=b.length;d--;)if(c.style[b[d]]==="")return!0;return!1},testTransform3d:function(){var a=!1;if(n.matchMedia)a=n.matchMedia("(-webkit-transform-3d)").matches;
return a}}}(),y=I.className,S=/(^| )a-mobile( |$)/.test(y),L=/(^| )a-tablet( |$)/.test(y),O={audio:function(){return!!b.createElement("audio").canPlayType},video:function(){return!!b.createElement("video").canPlayType},canvas:function(){return!!b.createElement("canvas").getContext},svg:function(){return!!b.createElementNS&&!!b.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},
dragDrop:function(){return"draggable"in b.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!n.history||!n.history.pushState)},webworker:function(){return!!n.Worker},autofocus:function(){return"autofocus"in b.createElement("input")},inputPlaceholder:function(){return"placeholder"in b.createElement("input")},textareaPlaceholder:function(){return"placeholder"in b.createElement("textarea")},localStorage:function(){return"localStorage"in n&&n.localStorage!==
null},orientation:function(){return"orientation"in n},touch:function(){return"ontouchend"in b},gradients:function(){return X.testGradients()},hires:function(){var a=n.devicePixelRatio&&n.devicePixelRatio>=1.5||n.matchMedia&&n.matchMedia("(min-resolution:144dpi)").matches;f("hiRes"+(S?"Mobile":L?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return X.testTransform3d()},touchScrolling:function(){return RegExp("Windowshop|android.([3-9]|[L-Z])|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|Chrome|Silk|Firefox|Trident"+
String.fromCharCode(92)+"/.+?; Touch","i").test(U)},ios:function(){return!!U.match(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)},android:function(){return!!U.match(/android.([1-9]|[L-Z])/i)&&!/trident/i.test(U)},mobile:function(){return S},tablet:function(){return L}},ca;for(ca in O)O.hasOwnProperty(ca)&&(O[ca]=w(O[ca]));for(var fa="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),da=0;da<fa.length;da++)O[fa[da]]=w(function(){return X.test(fa[da])});
var sa=!0,wa=0,ta={w:0,h:0},ua=4;t();typeof n.addEventListener==="function"?n.addEventListener("resize",u,!1):n.attachEvent("onresize",u);q(I,"a-no-js");r(I,"a-js");y=[];for(ca in O)O.hasOwnProperty(ca)&&O[ca]&&y.push("a-"+ca.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));r(I,y.join(" "));I.setAttribute("data-aui-build-date","3.15.7.4-2015-07-30");n.AmazonUIPageJS.register("p-detect",function(){return{capabilities:O,toggleResponsiveGrid:x,responsiveGridEnabled:C}})})(window,document,
Date);